[workspace]
resolver = "2"
members = [
    "crates/astroceleste-engine",
    "crates/astroceleste-engine-py",
    "crates/astroceleste-engine-wasm",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ffalcinelli/astroceleste-engine"
