// Generated once from the reference implementation's tables (charts/calc); this file
// is now the source of truth for the engine.

use super::Meaning;

/// Theme of each radix house when it becomes the derived Ascendant: (English, Italian).
pub const ROOT_HOUSE_THEMES: [(&str, &str); 12] = [
    ("Self & Vitality", "Sé & Vitalità"),
    ("Finances & Assets", "Finanze & Risorse"),
    ("Siblings & Communication", "Fratelli & Comunicazione"),
    ("Father, Home & Roots", "Padre, Famiglia & Radici"),
    ("Children & Creativity", "Figli & Creatività"),
    ("Health, Work & Pets", "Salute, Lavoro & Animali"),
    ("Partner, Spouse & Associates", "Partner, Coniuge & Soci"),
    ("Shared Resources & Crises", "Risorse Condivise & Crisi"),
    ("Higher Studies, Travels & In-Laws", "Studi Superiori, Viaggi & Suoceri"),
    ("Mother, Career & Honors", "Madre, Carriera & Successo"),
    ("Friends & Aspirations", "Amici & Aspirazioni"),
    ("Secrets & Hidden Enemies", "Segreti & Nemici Nascosti"),
];

/// DERIVED_HOUSE_MEANINGS[root - 1][house - 1].
pub const DERIVED_HOUSE_MEANINGS: [[Meaning; 12]; 12] = [
    [
        Meaning { en: "Self & Physical Body", it: "Sé & Corpo Fisico" },
        Meaning { en: "Personal Finances & Assets", it: "Finanze Personali & Risorse" },
        Meaning { en: "Siblings & Immediate Environment", it: "Fratelli & Ambiente Immediato" },
        Meaning { en: "Home, Father & Foundations", it: "Casa, Padre & Fondamenta" },
        Meaning { en: "Children, Romance & Pleasures", it: "Figli, Amore & Piaceri" },
        Meaning { en: "Health, Daily Work & Subordinates", it: "Salute, Lavoro Quotidiano & Collaboratori" },
        Meaning { en: "Spouse, Partners & Open Rivals", it: "Coniuge, Soci & Rivali Dichiarati" },
        Meaning { en: "Shared Resources, Crises & Transformation", it: "Risorse Condivise, Crisi & Trasformazione" },
        Meaning { en: "Higher Wisdom, Travels & Spirituality", it: "Saggezza Superiore, Viaggi & Spiritualità" },
        Meaning { en: "Mother, Career & Public Reputation", it: "Madre, Carriera & Reputazione Pubblica" },
        Meaning { en: "Friends, Benefactors & Hopes", it: "Amici, Benefattori & Speranze" },
        Meaning { en: "Subconscious, Secrets & Solitude", it: "Inconscio, Segreti & Solitudine" },
    ],
    [
        Meaning { en: "Movable Wealth & Capital", it: "Beni Mobili & Capitale" },
        Meaning { en: "Returns on Assets & Profits", it: "Rendimenti & Profitti" },
        Meaning { en: "Financial Documents & Contracts", it: "Documenti Finanziari & Contratti" },
        Meaning { en: "Real Estate Capital & Savings", it: "Capitale Immobiliare & Risparmi" },
        Meaning { en: "Financial Speculations & Risk", it: "Speculazioni Finanziarie & Rischio" },
        Meaning { en: "Maintenance Costs & Financial Burdens", it: "Costi di Mantenimento & Oneri" },
        Meaning { en: "Business Partners & Deals", it: "Partner Commerciali & Trattative" },
        Meaning { en: "Financial Losses & Debt Crises", it: "Perdite Finanziarie & Crisi di Debito" },
        Meaning { en: "Foreign Investments & Global Trade", it: "Investimenti Esteri & Commercio Globale" },
        Meaning { en: "Financial Standing & Credit Reputation", it: "Solidità Finanziaria & Reputazione Creditizia" },
        Meaning { en: "Dividends & Investment Incomes", it: "Dividendi & Rendite da Investimento" },
        Meaning { en: "Hidden Assets & Secret Accounts", it: "Beni Nascosti & Conti Segreti" },
    ],
    [
        Meaning { en: "Sibling, Relative or Neighbor", it: "Fratello/Sorella, Parente o Vicino" },
        Meaning { en: "Sibling's Wealth & Possessions", it: "Beni & Risorse del Fratello" },
        Meaning { en: "Sibling's Siblings & Communication", it: "Fratelli del Fratello & Comunicazione" },
        Meaning { en: "Sibling's Home, Land & Roots", it: "Casa & Radici del Fratello" },
        Meaning { en: "Sibling's Children (Nieces/Nephews)", it: "Figli del Fratello (Nipoti)" },
        Meaning { en: "Sibling's Health & Daily Tasks", it: "Salute & Lavoro del Fratello" },
        Meaning { en: "Sibling's Spouse & Partnerships", it: "Coniuge & Soci del Fratello" },
        Meaning { en: "Sibling's Crises & Inherited Assets", it: "Crisi & Eredità del Fratello" },
        Meaning { en: "Sibling's Higher Education & Beliefs", it: "Studi Superiori & Viaggi del Fratello" },
        Meaning { en: "Sibling's Career & Public Status", it: "Carriera & Status del Fratello" },
        Meaning { en: "Sibling's Friends & Aspirations", it: "Amici & Aspirazioni del Fratello" },
        Meaning { en: "Sibling's Secrets & Hidden Troubles", it: "Segreti & Difficoltà Nascoste del Fratello" },
    ],
    [
        Meaning { en: "Father, Ancestor or Homeland", it: "Padre, Antenato o Patria" },
        Meaning { en: "Father's Wealth & Movable Goods", it: "Beni & Denaro del Padre" },
        Meaning { en: "Father's Siblings (Paternal Uncles/Aunts)", it: "Fratelli del Padre (Zii Paterni)" },
        Meaning { en: "Father's Father (Paternal Grandfather)", it: "Padre del Padre (Nonno Paterno)" },
        Meaning { en: "Father's Children (Native's Siblings)", it: "Figli del Padre (Fratelli del Nativo)" },
        Meaning { en: "Father's Health, Sickness & Staff", it: "Salute & Collaboratori del Padre" },
        Meaning { en: "Father's Wife (Mother)", it: "Moglie del Padre (Madre)" },
        Meaning { en: "Father's Legacy, Debts & Longevity", it: "Eredità & Longevità del Padre" },
        Meaning { en: "Father's Philosophy & Long Journeys", it: "Filosofia & Viaggi del Padre" },
        Meaning { en: "Father's Profession & Honors", it: "Professione & Onori del Padre" },
        Meaning { en: "Father's Friends & Acquired Hopes", it: "Amici & Speranze del Padre" },
        Meaning { en: "Father's Sorrows & Hidden Enemies", it: "Afflizioni & Nemici Nascosti del Padre" },
    ],
    [
        Meaning { en: "First Child, Romance or Creation", it: "Primo Figlio, Amore o Creazione" },
        Meaning { en: "Child's Assets & Wealth", it: "Beni & Risorse del Figlio" },
        Meaning { en: "Child's Primary Studies & Siblings", it: "Studi Primari & Fratelli del Figlio" },
        Meaning { en: "Child's Residence & Ancestry", it: "Casa & Famiglia del Figlio" },
        Meaning { en: "Child's Children (Grandchildren)", it: "Figli del Figlio (Nipoti di Nonno)" },
        Meaning { en: "Child's Health & Routine", it: "Salute & Routine del Figlio" },
        Meaning { en: "Child's Partner (Son/Daughter-in-Law)", it: "Partner del Figlio (Genero/Nuora)" },
        Meaning { en: "Child's Shared Assets & Crises", it: "Risorse Condivise & Crisi del Figlio" },
        Meaning { en: "Child's Higher Studies & Travels", it: "Studi Universitari & Viaggi del Figlio" },
        Meaning { en: "Child's Career & Achievements", it: "Carriera & Riconoscimenti del Figlio" },
        Meaning { en: "Child's Friends & Social Circle", it: "Amici & Circolo Sociale del Figlio" },
        Meaning { en: "Child's Hidden Fears & Obstacles", it: "Paure Nascoste & Ostacoli del Figlio" },
    ],
    [
        Meaning { en: "Employee, Pet or Health Issue", it: "Collaboratore, Animale Domestico o Malattia" },
        Meaning { en: "Employee's Wages / Pet Expenses", it: "Salari dei Dipendenti / Spese per Animali" },
        Meaning { en: "Employee's Communications & Tasks", it: "Comunicazioni & Mansioni del Personale" },
        Meaning { en: "Workplace Environment / Root Cause of Illness", it: "Ambiente di Lavoro / Causa Prima della Malattia" },
        Meaning { en: "Therapy Remedies & Work Creative Output", it: "Terapie & Creatività Lavorativa" },
        Meaning { en: "Secondary Health Complications", it: "Complicazioni Secondarie di Salute" },
        Meaning { en: "Physician, Veterinarian or Coworker", it: "Medico Curante, Veterinario o Collega" },
        Meaning { en: "Chronic Crisis & Employee Liabilities", it: "Crisi Cronica & Oneri dei Dipendenti" },
        Meaning { en: "Medical Advice & Treatment Journeys", it: "Consulti Medici & Viaggi Terapeutici" },
        Meaning { en: "Clinical Diagnosis & Employer Authority", it: "Diagnosi Clinica & Autorità del Datore" },
        Meaning { en: "Recovery Prospects & Helpful Allies", it: "Prospettive di Guarigione & Aiuti" },
        Meaning { en: "Hospitalization & Hidden Sickness Factors", it: "Ricovero & Fattori Nascosti della Malattia" },
    ],
    [
        Meaning { en: "Partner, Spouse or Business Associate", it: "Partner, Coniuge o Socio" },
        Meaning { en: "Partner's Wealth & Possessions", it: "Beni & Risorse del Partner" },
        Meaning { en: "Partner's Siblings & Communications", it: "Fratelli & Comunicazioni del Partner" },
        Meaning { en: "Partner's Parents, Family & Home", it: "Genitori, Famiglia & Casa del Partner" },
        Meaning { en: "Partner's Children & Pleasures", it: "Figli & Piaceri del Partner" },
        Meaning { en: "Partner's Health, Sickness & Work", it: "Salute, Malattie & Lavoro del Partner" },
        Meaning { en: "Partner's Partner (The Native)", it: "Partner del Partner (Il Nativo)" },
        Meaning { en: "Partner's Shared Finances & Crises", it: "Finanze Condivise & Crisi del Partner" },
        Meaning { en: "Partner's In-Laws, Higher Studies & Travels", it: "Suoceri, Studi Superiori & Viaggi del Partner" },
        Meaning { en: "Partner's Mother, Career & Reputation", it: "Madre, Carriera & Reputazione del Partner" },
        Meaning { en: "Partner's Friends, Hopes & Earnings", it: "Amici, Speranze & Guadagni del Partner" },
        Meaning { en: "Partner's Secrets, Anxieties & Confinement", it: "Segreti, Angosce & Isolamento del Partner" },
    ],
    [
        Meaning { en: "Inheritance, Debt & Shared Capital", it: "Eredità, Debiti & Capitale Condiviso" },
        Meaning { en: "Debt Collection & Liquidation Gains", it: "Recupero Crediti & Liquidazioni" },
        Meaning { en: "Wills, Deeds & Legal Notices", it: "Testamenti, Atti & Notifiche Legali" },
        Meaning { en: "Ancestral Estate & Conclusion of Crises", it: "Patrimonio Ancestrale & Fine delle Crisi" },
        Meaning { en: "Profits from Transformation & Legacies", it: "Profitti da Trasformazioni & Eredità" },
        Meaning { en: "Settlement Efforts & Resolution Burdens", it: "Pratiche Successorie & Oneri di Risoluzione" },
        Meaning { en: "Creditors & Financial Counterparties", it: "Creditori & Controparti Finanziarie" },
        Meaning { en: "Deep Metamorphosis & Extreme Crises", it: "Metamorfosi Profonda & Crisi Estreme" },
        Meaning { en: "Spiritual Meaning of Crises & Foreign Assets", it: "Senso Spirituale della Crisi & Beni Esteri" },
        Meaning { en: "Public Estate Probate & Status Post-Crisis", it: "Successione Pubblica & Status Post-Crisi" },
        Meaning { en: "Allies in Crisis & Relief Funding", it: "Alleati nella Crisi & Finanziamenti di Soccorso" },
        Meaning { en: "Hidden Debts & Secret Inheritance Feuds", it: "Debiti Nascosti & Faide Ereditarie Segrete" },
    ],
    [
        Meaning { en: "Teacher, Guru, In-Law or Foreign Country", it: "Maestro, Guida, Suocero o Paese Straniero" },
        Meaning { en: "Mentor's Wealth / Travel Funds", it: "Beni del Maestro / Fondi di Viaggio" },
        Meaning { en: "Sacred Texts & Philosophic Discourse", it: "Testi Sacri & Discorsi Filosofici" },
        Meaning { en: "Spiritual Sanctuary & Homeland of In-Laws", it: "Santuario Spirituale & Patria dei Suoceri" },
        Meaning { en: "Disciples, Students & Joys of Pilgrimage", it: "Discepoli, Studenti & Gioie del Pellegrinaggio" },
        Meaning { en: "Spiritual Discipline & Ministry Duties", it: "Disciplina Spirituale & Doveri di Ministero" },
        Meaning { en: "Mentor's Spouse & In-Law Partnerships", it: "Coniuge del Maestro & Legami dei Suoceri" },
        Meaning { en: "Esoteric Mysteries & Shared Lineage", it: "Misteri Esoterici & Tradizione Condivisa" },
        Meaning { en: "High Transcendence & Overseas Pilgrimages", it: "Alta Trascendenza & Pellegrinaggi d'Oltremare" },
        Meaning { en: "Spiritual Authority & Academic Standing", it: "Autorità Spirituale & Prestigio Accademico" },
        Meaning { en: "Spiritual Community & Global Network", it: "Comunità Spirituale (Sangha) & Rete Globale" },
        Meaning { en: "Monastic Retreat & Hermit Solitude", it: "Ritiro Monastico & Solitudine Eremitica" },
    ],
    [
        Meaning { en: "Mother, Profession or Authority Figure", it: "Madre, Professione o Figura di Autorità" },
        Meaning { en: "Mother's Wealth & Business Capital", it: "Beni della Madre & Capitale d'Impresa" },
        Meaning { en: "Mother's Siblings (Maternal Uncles/Aunts)", it: "Fratelli della Madre (Zii Materni)" },
        Meaning { en: "Mother's Father (Maternal Grandfather)", it: "Padre della Madre (Nonno Materno)" },
        Meaning { en: "Mother's Creativity & Pleasures", it: "Creatività & Piaceri della Madre" },
        Meaning { en: "Mother's Health, Sickness & Work Staff", it: "Salute, Malattie & Collaboratori della Madre" },
        Meaning { en: "Mother's Husband (Father)", it: "Marito della Madre (Padre)" },
        Meaning { en: "Mother's Legacies, Debts & Crisis", it: "Eredità, Debiti & Crisi della Madre" },
        Meaning { en: "Mother's Philosophy & Long Travels", it: "Filosofia & Viaggi della Madre" },
        Meaning { en: "Mother's Mother (Maternal Grandmother) / Career Apex", it: "Madre della Madre (Nonna Materna) / Apice della Carriera" },
        Meaning { en: "Mother's Friends, Sponsors & Public Allies", it: "Amici, Sponsor & Alleati della Madre" },
        Meaning { en: "Mother's Hidden Worries & Solitude", it: "Preoccupazioni Segrete & Isolamento della Madre" },
    ],
    [
        Meaning { en: "Friend, Association or Community Group", it: "Amico, Associazione o Gruppo Comunitario" },
        Meaning { en: "Friend's Assets & Group Treasury", it: "Beni dell'Amico & Cassa dell'Associazione" },
        Meaning { en: "Friend's Siblings & Group Newsletters", it: "Fratelli dell'Amico & Notiziari del Gruppo" },
        Meaning { en: "Friend's Home & Community Clubhouse", it: "Casa dell'Amico & Sede dell'Associazione" },
        Meaning { en: "Friend's Children & Creative Projects", it: "Figli dell'Amico & Progetti Creativi" },
        Meaning { en: "Friend's Health & Volunteer Labor", it: "Salute dell'Amico & Lavoro Volontario" },
        Meaning { en: "Friend's Partner & Group Coalitions", it: "Partner dell'Amico & Coalizioni" },
        Meaning { en: "Friend's Crises & Shared Association Assets", it: "Crisi dell'Amico & Fondi Condivisi" },
        Meaning { en: "Friend's Higher Ideals & Conferences", it: "Ideali Superiori dell'Amico & Convegni" },
        Meaning { en: "Friend's Career & Group Leadership", it: "Carriera dell'Amico & Leadership del Gruppo" },
        Meaning { en: "Friend's Friends & Secondary Networks", it: "Amici dell'Amico & Reti Secondarie" },
        Meaning { en: "Friend's Hidden Troubles & Secret Rivals", it: "Difficoltà Nascoste & Rivali Segreti dell'Amico" },
    ],
    [
        Meaning { en: "Secret Foe, Inner Sanctuary or Subconscious", it: "Nemico Nascosto, Santuario Interiore o Inconscio" },
        Meaning { en: "Hidden Funds & Money Spent in Confinement", it: "Fondi Nascosti & Spese di Degenza" },
        Meaning { en: "Secret Communications & Confessions", it: "Comunicazioni Segrete & Confessioni" },
        Meaning { en: "Hidden Foundations & Ancestral Roots", it: "Fondamenta Nascoste & Radici Ancestrali" },
        Meaning { en: "Secret Pleasures & Hidden Creativity", it: "Piaceri Segreti & Creatività Celata" },
        Meaning { en: "Confinement Ailments & Solitary Duties", it: "Disturbi da Isolamento & Doveri Solitari" },
        Meaning { en: "Secret Rival's Partner & Open Revelation", it: "Partner del Nemico Nascosto & Rivelazione" },
        Meaning { en: "Subconscious Metamorphosis & Extreme Secrecy", it: "Metamorfosi Inconscia & Segretezza Estrema" },
        Meaning { en: "Mystical Pilgrimage & Overseas Sanctuary", it: "Pellegrinaggio Mistico & Rifugio all'Estero" },
        Meaning { en: "Public Unveiling of Secrets & Spiritual Vocation", it: "Svelamento di Segreti & Vocazione Spirituale" },
        Meaning { en: "Secret Benefactors & Unknown Patrons", it: "Benefattori Segreti & Mecenati Sconosciuti" },
        Meaning { en: "Deepest Karma & Ultimate Transcendence", it: "Karma Profondo & Trascendenza Finale" },
    ],
];
