"""Generate the engine's embedded data tables.

    uv run --no-project --with skyfield==1.55 --with numpy \
        scripts/gen_tables.py path/to/chiron_1849_2151.npz

The engine reproduces Skyfield 1.55 bit for bit where it can, so the ΔT and nutation
tables are taken from Skyfield's own bundled data (MIT, see NOTICE):

  src/data/deltat.bin          daily IERS ΔT table + the long-term spline curve Skyfield
                               builds around it (evaluated exactly as Skyfield does)
  src/frames/nutation_data.rs  IAU 2000A nutation series and the complementary terms of
                               the equation of the equinoxes
  src/data/chiron.bin          Chiron geocentric longitude table (4-day step, 1849-2151)

All binary files are little-endian.
"""

import struct
import sys
from pathlib import Path

import numpy as np
import skyfield
from skyfield.api import load
from skyfield.functions import load_bundled_npy

CRATE = Path(__file__).resolve().parents[1] / "crates" / "astroceleste-engine" / "src"


def write_deltat() -> None:
    arrays = load_bundled_npy("iers.npz")
    offsets = arrays["tt_jd_minus_arange"]
    delta_t_1e7 = arrays["delta_t_1e7"]
    assert np.all(delta_t_1e7 == np.round(delta_t_1e7)) and abs(delta_t_1e7).max() < 2**31

    # `tt_jd_minus_arange` only changes at leap seconds: store it run-length encoded.
    runs = [(0, offsets[0])]
    for i in range(1, len(offsets)):
        if offsets[i] != offsets[i - 1]:
            runs.append((i, offsets[i]))

    curve = load.timescale().delta_t_function.long_term_function.table
    assert curve.shape[0] == 6

    out = bytearray()
    out += struct.pack("<I", len(offsets))
    out += struct.pack("<I", len(runs))
    for start, value in runs:
        out += struct.pack("<Id", start, value)
    out += delta_t_1e7.astype("<i4").tobytes()
    out += struct.pack("<I", curve.shape[1])
    out += np.ascontiguousarray(curve.T).astype("<f8").tobytes()  # one row per spline
    (CRATE / "data" / "deltat.bin").write_bytes(bytes(out))
    print(f"deltat.bin: {len(offsets)} days, {len(runs)} runs, {curve.shape[1]} splines")


def rust_array(name: str, rust_type: str, values: np.ndarray) -> str:
    if values.ndim == 1:
        body = ", ".join(repr_value(v, rust_type) for v in values)
        return f"pub const {name}: [{rust_type}; {len(values)}] = [{body}];\n"
    rows = ",\n    ".join(
        "[" + ", ".join(repr_value(v, rust_type) for v in row) + "]" for row in values
    )
    return (
        f"pub const {name}: [[{rust_type}; {values.shape[1]}]; {values.shape[0]}] = [\n"
        f"    {rows},\n];\n"
    )


def repr_value(value, rust_type: str) -> str:
    if rust_type == "f64":
        text = repr(float(value))
        return text if ("." in text or "e" in text or "inf" in text) else text + ".0"
    return str(int(value))


def write_nutation() -> None:
    a = load_bundled_npy("nutation.npz")
    parts = [
        "// @generated by scripts/gen_tables.py from Skyfield's nutation.npz (MIT, see NOTICE).\n",
        "// Do not edit by hand.\n\n",
        rust_array("NALS_T", "i8", a["nals_t"]),
        rust_array("LUNISOLAR_LONGITUDE", "f64", a["lunisolar_longitude_coefficients"]),
        rust_array("LUNISOLAR_OBLIQUITY", "f64", a["lunisolar_obliquity_coefficients"]),
        rust_array("NAPL_T", "i8", a["napl_t"]),
        rust_array("PLANETARY_LONGITUDE", "f64", a["nutation_coefficients_longitude"]),
        rust_array("PLANETARY_OBLIQUITY", "f64", a["nutation_coefficients_obliquity"]),
        rust_array("KE0_T", "i8", a["ke0_t"]),
        rust_array("KE1", "i8", a["ke1"]),
        rust_array("SE0_T_0", "f64", a["se0_t_0"]),
        rust_array("SE0_T_1", "f64", a["se0_t_1"]),
    ]
    (CRATE / "frames" / "nutation_data.rs").write_text("".join(parts), encoding="utf-8")
    print("nutation_data.rs written")


def write_chiron(npz_path: Path) -> None:
    data = np.load(npz_path)
    lons = np.asarray(data["lons_unwrapped"], dtype="<f8")
    out = struct.pack("<ddI", float(data["jd_start"]), float(data["step"]), len(lons))
    (CRATE / "data" / "chiron.bin").write_bytes(out + lons.tobytes())
    print(f"chiron.bin: {len(lons)} samples")


def main() -> None:
    assert skyfield.__version__ == "1.55", f"expected Skyfield 1.55, got {skyfield.__version__}"
    (CRATE / "data").mkdir(exist_ok=True)
    (CRATE / "frames").mkdir(exist_ok=True)
    write_deltat()
    write_nutation()
    write_chiron(Path(sys.argv[1]))


if __name__ == "__main__":
    main()
